<?php
session_start();
if (!isset($_SESSION['username'])) {
    header("Location: login.php");
    exit();
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Dashboard</title>
<link rel="stylesheet" href="style.css">
<script>
function updateDateTime() {
  const now = new Date();
  document.getElementById('datetime').textContent = now.toLocaleString();
}
setInterval(updateDateTime, 1000);
window.onload = updateDateTime;
</script>
</head>
<body>
<div class="dashboard-container">

    <!-- Sidebar (included) -->
    <?php include __DIR__ . '/includes/sidebar.php'; ?>

    <!-- Main Content -->
    <main class="main-content">
        <header class="topbar">
            <div class="topbar-left">
                <h1>Dashboard</h1>
                <p id="datetime"></p>
            </div>
            <div class="profile">
                <img src="https://cdn-icons-png.flaticon.com/512/3135/3135715.png" alt="User" class="profile-icon">
            </div>
        </header>

        <!-- Overview Cards -->
        <section class="cards">
            <div class="card">
                <h3>Total Enrolled Students</h3>
                <p>441</p>
            </div>
            <div class="card">
                <h3>Pending Enrollments</h3>
                <p>36</p>
            </div>
            <div class="card">
                <h3>Active Sections</h3>
                <p>22</p>
            </div>
            <div class="card">
                <h3>Total Payments</h3>
                <p>₱500.1K</p>
            </div>
        </section>

        <!-- Quick Actions -->
        <section class="quick-actions">
            <h2>Quick Actions</h2>
            <div class="action-buttons">
                <button>Add New Student</button>
                <button>Generate Report</button>
                <button>Create Schedule</button>
                <button>Record Payment</button>
            </div>
        </section>

        <!-- Recent Activity -->
        <section class="activity-log">
            <h2>Recent Activities</h2>
            <ul>
                <li>✅ Student <b>Maria Santos</b> successfully enrolled.</li>
                <li>💰 Payment of ₱15,000 recorded for <b>John Dela Cruz</b>.</li>
                <li>🕓 Class schedule updated for <b>Grade 3 - Section A</b>.</li>
                <li>📄 Enrollment report generated by <b>CliffLozada</b>.</li>
                <li>⚙️ User <b>AceToralba</b> updated system settings.</li>
            </ul>
        </section>

        <!-- Welcome -->
        <section class="welcome">
            <h2>Welcome to the Dashboard</h2>
            <p>Use the modules on the left to manage enrollment, records, and reports efficiently.</p>
        </section>
    </main>
</div>

<script>
    // Highlight active menu item
    const items = document.querySelectorAll('.menu-item');
    items.forEach(item => {
        item.addEventListener('click', () => {
            items.forEach(i => i.classList.remove('active'));
            item.classList.add('active');
        });
    });
</script>
</body>
</html>
